version: '3'

services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin_password
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - EXECUTE_COMMANDS=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./scripts:/scripts
      - ./workflows:/workflows
      - ./credentials:/credentials
    entrypoint: ["/scripts/startup.sh"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  n8n_data:
